#!/bin/sh
 
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/var/www/mooviefish.com/app/run.sh
PIDDIR=/var/www/mooviefish.com/app/tmp/pids
PIDFILE="$PIDDIR/mooviefishsrv.pid"
USER="www-data"
 
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
if [ ! -d $PIDDIR ]; then
  mkdir $PIDDIR
  chown $USER.$USER $PIDDIR
fi
 
case "$1" in
  start)
    start-stop-daemon --start --quiet --oknodo --background --pidfile $PIDFILE --exec $DAEMON --chuid $USER -- $SERVICES_OPTS
    sleep 5
    $0 status
  ;;
 
  stop)
    if start-stop-daemon --stop --quiet --pidfile $PIDFILE; then
      exit 0
    else
      exit 1
    fi
  ;;
esac
